const emails = [
    {
        id: 1,
        sender: "Test",
        title: "Meeting Reminder Meeting Reminder Meeting Reminder Meeting Reminder",
        content: "Don't forget about the meeting at 10 AM tomorrow. Don't forget about the meeting at 10 AM tomorrow. Don't forget about the meeting at 10 AM tomorrow.",
        date: "2024-11-01",
        isChecked: true,
        isStarred: true,
        isImportant: true,
    },
    {
        id: 2,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 3,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 4,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 5,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 6,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 7,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 8,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 9,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 10,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 11,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 12,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 13,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 14,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 15,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 16,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 17,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 18,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 19,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    }, //add new emails not only from university
    {
        id: 20,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 21,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    }, 
    {
        id: 22,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    }, 
    {
        id: 23,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    }, 
    {
        id: 24,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    }, 
    {
        id: 25,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 26,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 27,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 28,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 29,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 30,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 31,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    }, 
    {
        id: 32,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    }, 
    {
        id: 33,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    }, 
    {
        id: 34,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    }, 
    {
        id: 35,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 36,
        sender: "Jane Smith",
        title: "Project Update",
        content: "The project is on track for completion next week.",
        date: "2024-10-31",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 37,
        sender: "HR Department University",
        title: "Job Offer",
        content: "We are pleased to offer you a position at our company.",
        date: "2024-10-30",
        isChecked: false,
        isStarred: false
    }
];

export default emails;
