const emails = [
    {
        id: 1,
        sender: "Alex Johnson",
        title: "Weekly Standup Notes",
        content: "Hi team, please find attached the notes from this week's standup meeting.",
        date: "2023-11-20",
        isChecked: false,
        isStarred: true,
        isImportant: true,
    },
    {
        id: 2,
        sender: "Emily Parker",
        title: "Dinner Plans?",
        content: "Hey! Are we still on for dinner this Friday? Let me know!",
        date: "2024-11-19",
        isChecked: true,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 3,
        sender: "Netflix",
        title: "Your November Invoice",
        content: "Your subscription for November has been processed successfully.",
        date: "2024-11-18",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 4,
        sender: "IT Support",
        title: "Scheduled Maintenance Alert",
        content: "Our systems will be undergoing maintenance this Saturday from 1 AM to 5 AM.",
        date: "2024-11-17",
        isChecked: false,
        isStarred: false,
        isImportant: true,
    },
    {
        id: 5,
        sender: "Mom",
        title: "Grandpa's Birthday",
        content: "Don’t forget, we’re celebrating Grandpa’s birthday on Sunday at 3 PM.",
        date: "2024-11-16",
        isChecked: true,
        isStarred: true,
        isImportant: true,
    },
    {
        id: 6,
        sender: "Amazon",
        title: "Your Order Has Shipped",
        content: "Your order #12345 has been shipped and will arrive by November 23.",
        date: "2024-11-15",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 7,
        sender: "HR Department",
        title: "Employee Wellness Survey",
        content: "We value your feedback! Please complete the attached survey by Friday.",
        date: "2024-11-14",
        isChecked: false,
        isStarred: true,
        isImportant: true,
    },
    {
        id: 8,
        sender: "Dr. Smith",
        title: "Appointment Reminder",
        content: "This is a reminder for your appointment on November 22 at 10:30 AM.",
        date: "2024-11-13",
        isChecked: true,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 9,
        sender: "Spotify",
        title: "Your Wrapped Is Ready!",
        content: "Your Spotify Wrapped 2024 is here. See your top songs and artists!",
        date: "2024-11-12",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 10,
        sender: "Jessica Lee",
        title: "Photos From the Wedding",
        content: "Hey, sharing the photos from last weekend’s wedding. Hope you like them!",
        date: "2024-11-11",
        isChecked: true,
        isStarred: true,
        isImportant: false,
    },
    {
        id: 11,
        sender: "LinkedIn",
        title: "Your Weekly Job Update",
        content: "Here are some new job recommendations based on your profile.",
        date: "2024-11-10",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 12,
        sender: "David Green",
        title: "Golf This Weekend?",
        content: "Hi! Are you free to hit the golf course this Saturday morning?",
        date: "2024-11-09",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 13,
        sender: "Slack",
        title: "Your Daily Digest",
        content: "Catch up on what you missed from your channels and direct messages.",
        date: "2024-11-08",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 14,
        sender: "Bank of America",
        title: "Statement Available",
        content: "Your monthly account statement is now available to view online.",
        date: "2024-11-07",
        isChecked: true,
        isStarred: false,
        isImportant: true,
    },
    {
        id: 15,
        sender: "Liam Thomas",
        title: "Weekend Road Trip",
        content: "Let’s finalize the plans for the weekend road trip. Call me later!",
        date: "2024-11-06",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 16,
        sender: "Coursera",
        title: "Finish Your Course",
        content: "You’re just 3 lessons away from completing your Python for Beginners course!",
        date: "2024-11-05",
        isChecked: false,
        isStarred: true,
        isImportant: false,
    },
    {
        id: 17,
        sender: "Local Library",
        title: "Overdue Book Notice",
        content: "The book 'Atomic Habits' is overdue. Please return it to avoid late fees.",
        date: "2024-11-04",
        isChecked: false,
        isStarred: false,
        isImportant: true,
    },
    {
        id: 18,
        sender: "Sarah Connor",
        title: "Yoga Class Tomorrow",
        content: "Don’t forget our yoga class tomorrow at 6 PM. See you there!",
        date: "2024-11-03",
        isChecked: true,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 19,
        sender: "Google",
        title: "Verify Your Login Attempt",
        content: "A login attempt was detected from a new device. If this wasn’t you, secure your account.",
        date: "2024-11-02",
        isChecked: false,
        isStarred: true,
        isImportant: true,
    },
    {
        id: 20,
        sender: "John Doe",
        title: "Catch Up Soon?",
        content: "It’s been a while! Let’s catch up over coffee next week?",
        date: "2024-11-01",
        isChecked: true,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 21,
        sender: "Olivia Martinez",
        title: "Presentation Feedback",
        content: "Hi, I’ve attached my feedback for your presentation. Let me know if you need anything else.",
        date: "2024-11-20",
        isChecked: false,
        isStarred: true,
        isImportant: false,
    },
    {
        id: 22,
        sender: "Apple",
        title: "Your Apple ID Security Alert",
        content: "Your Apple ID was used to sign in from a new device. If this wasn’t you, please update your password.",
        date: "2024-11-19",
        isChecked: false,
        isStarred: false,
        isImportant: true,
    },
    {
        id: 23,
        sender: "Gym Membership",
        title: "Membership Renewal",
        content: "Your annual gym membership is up for renewal. Renew today to enjoy a 10% discount!",
        date: "2024-11-18",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 24,
        sender: "Twitter",
        title: "Trending Today",
        content: "Check out the top trends in your area today!",
        date: "2024-11-17",
        isChecked: true,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 25,
        sender: "Sophia Carter",
        title: "Recipe for the Cookies",
        content: "Hi, I’m sharing the cookie recipe we talked about. Hope you enjoy it!",
        date: "2024-11-16",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 26,
        sender: "Uber",
        title: "Your Ride Receipt",
        content: "Thanks for riding with us! Your receipt for November 15 is attached.",
        date: "2024-11-15",
        isChecked: true,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 27,
        sender: "Vacation Rentals",
        title: "Special Deals for the Holidays",
        content: "Plan your perfect holiday getaway with our exclusive discounts.",
        date: "2024-11-14",
        isChecked: false,
        isStarred: true,
        isImportant: false,
    },
    {
        id: 28,
        sender: "Local Community Center",
        title: "Volunteer Opportunity",
        content: "We’re looking for volunteers for this year’s food drive. Join us to make a difference!",
        date: "2024-11-13",
        isChecked: false,
        isStarred: false,
        isImportant: true,
    },
    {
        id: 29,
        sender: "Emily Walker",
        title: "Project Draft Attached",
        content: "Hi, I’ve attached the first draft of the project. Looking forward to your feedback.",
        date: "2024-11-12",
        isChecked: true,
        isStarred: true,
        isImportant: true,
    },
    {
        id: 30,
        sender: "Reddit",
        title: "Your Weekly Reddit Digest",
        content: "Here are the top posts from the communities you follow.",
        date: "2024-11-11",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 31,
        sender: "Dr. Patel",
        title: "Lab Results Available",
        content: "Your lab results are ready for review. Please check the portal.",
        date: "2024-11-10",
        isChecked: false,
        isStarred: false,
        isImportant: true,
    },
    {
        id: 32,
        sender: "Taylor & Co.",
        title: "Black Friday Sale",
        content: "Exclusive early access to our Black Friday sale starts now!",
        date: "2024-11-09",
        isChecked: true,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 33,
        sender: "Bank Alert",
        title: "Unusual Activity Detected",
        content: "We detected unusual activity on your account. Please review your transactions.",
        date: "2024-11-08",
        isChecked: false,
        isStarred: true,
        isImportant: true,
    },
    {
        id: 34,
        sender: "Mark Stevenson",
        title: "Game Night This Friday",
        content: "Hey, are you joining us for game night? Let me know!",
        date: "2024-11-07",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 35,
        sender: "Hulu",
        title: "Watch the Latest Episodes",
        content: "Catch up on the latest episodes of your favorite shows!",
        date: "2024-11-06",
        isChecked: true,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 36,
        sender: "Shopify",
        title: "Order Confirmation",
        content: "Thank you for your order! Your order #56789 is being processed.",
        date: "2024-11-05",
        isChecked: false,
        isStarred: false,
        isImportant: false,
    },
    {
        id: 37,
        sender: "Workplace Safety",
        title: "New Safety Guidelines",
        content: "Please review the updated workplace safety guidelines by Monday.",
        date: "2024-11-04",
        isChecked: false,
        isStarred: true,
        isImportant: true,
    },
    {
        id: 38,
        sender: "Lily Brown",
        title: "Happy Birthday!",
        content: "Wishing you the happiest of birthdays! Let’s celebrate soon.",
        date: "2024-11-03",
        isChecked: false,
        isStarred: true,
        isImportant: false,
    },
    {
        id: 39,
        sender: "Zoom",
        title: "Meeting Reminder",
        content: "Reminder: You have a Zoom meeting scheduled for November 20 at 2 PM.",
        date: "2024-11-02",
        isChecked: false,
        isStarred: false,
        isImportant: true,
    },
    {
        id: 40,
        sender: "National Geographic",
        title: "Renew Your Subscription",
        content: "Don’t miss out on next month’s issue. Renew your subscription today.",
        date: "2024-11-01",
        isChecked: true,
        isStarred: false,
        isImportant: false,
    },
];

export default emails;
